'''
Neuron simulator export for:

Components:
    oscillator_sim (Type: Generic2dOscillator:  tau=0.00125 (SI per_time) I=0.0 (dimensionless) a=1.05 (dimensionless) b=-1.0 (dimensionless) c=0.0 (dimensionless) d=0.1 (dimensionless) e=0.0 (dimensionless) f=0.33 (dimensionless) g=1.0 (dimensionless) alpha=1.0 (dimensionless) beta=0.2 (dimensionless) gamma=-1.0 (dimensionless) c_0=0.0 (dimensionless) lc_0=0.0 (dimensionless))
    sim1 (Type: Simulation:  length=0.08 (SI time) step=1.0E-5 (SI time))


    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.0
         org.neuroml.model   v1.5.0
         jLEMS               v0.9.8.7

'''

import neuron

import time

import hashlib
h = neuron.h
h.load_file("stdlib.hoc")

h.load_file("stdgui.hoc")

h("objref p")
h("p = new PythonObject()")

class NeuronSimulation():

    def __init__(self, tstop, dt, seed=123456789):

        print("\n    Starting simulation in NEURON generated from NeuroML2 model...\n")

        self.seed = seed
        self.randoms = []
        self.next_global_id = 0  # Used in Random123 classes for elements using random(), etc. 

        self.next_spiking_input_id = 0  # Used in Random123 classes for elements using random(), etc. 

        '''
        Adding simulation Component(id=sim1 type=Simulation) of network/component: oscillator_sim (Type: Generic2dOscillator:  tau=0.00125 (SI per_time) I=0.0 (dimensionless) a=1.05 (dimensionless) b=-1.0 (dimensionless) c=0.0 (dimensionless) d=0.1 (dimensionless) e=0.0 (dimensionless) f=0.33 (dimensionless) g=1.0 (dimensionless) alpha=1.0 (dimensionless) beta=0.2 (dimensionless) gamma=-1.0 (dimensionless) c_0=0.0 (dimensionless) lc_0=0.0 (dimensionless))
        
        '''
        # ######################   Population: population_null
        print("Population population_null contains 1 instance(s) of component: oscillator_sim of type: Generic2dOscillator")

        h(" {n_population_null = 1} ")
        '''
        Population population_null contains instances of Component(id=oscillator_sim type=Generic2dOscillator)
        whose dynamics will be implemented as a mechanism (oscillator_sim) in a mod file
        '''
        h(" create population_null[1]")
        h(" objectvar m_oscillator_sim_population_null[1] ")

        for i in range(int(h.n_population_null)):
            h.population_null[i].L = 10.0
            h.population_null[i](0.5).diam = 10.0
            h.population_null[i](0.5).cm = 318.31927
            h.population_null[i].push()
            h(" population_null[%i]  { m_oscillator_sim_population_null[%i] = new oscillator_sim(0.5) } "%(i,i))

            h.m_oscillator_sim_population_null[i].tau = 1.2500001E-6
            h.m_oscillator_sim_population_null[i].I = NaN
            h.m_oscillator_sim_population_null[i].a = NaN
            h.m_oscillator_sim_population_null[i].b = NaN
            h.m_oscillator_sim_population_null[i].c = NaN
            h.m_oscillator_sim_population_null[i].d = NaN
            h.m_oscillator_sim_population_null[i].e = NaN
            h.m_oscillator_sim_population_null[i].f = NaN
            h.m_oscillator_sim_population_null[i].g = NaN
            h.m_oscillator_sim_population_null[i].alpha = NaN
            h.m_oscillator_sim_population_null[i].beta = NaN
            h.m_oscillator_sim_population_null[i].gamma = NaN
            h.m_oscillator_sim_population_null[i].c_0 = NaN
            h.m_oscillator_sim_population_null[i].lc_0 = NaN
            h.pop_section()

            self.next_global_id+=1


        trec = h.Vector()
        trec.record(h._ref_t)

        h.tstop = tstop

        h.dt = dt

        h.steps_per_ms = 1/h.dt



        # ######################   File to save: time.dat (time)
        # Column: time
        h(' objectvar v_time ')
        h(' { v_time = new Vector() } ')
        h(' { v_time.record(&t) } ')
        h.v_time.resize((h.tstop * h.steps_per_ms) + 1)

        self.initialized = False

        self.sim_end = -1 # will be overwritten

    def run(self):

        self.initialized = True
        sim_start = time.time()
        print("Running a simulation of %sms (dt = %sms; seed=%s)" % (h.tstop, h.dt, self.seed))

        h.run()

        self.sim_end = time.time()
        sim_time = self.sim_end - sim_start
        print("Finished NEURON simulation in %f seconds (%f mins)..."%(sim_time, sim_time/60.0))

        self.save_results()


    def advance(self):

        if not self.initialized:
            h.finitialize()
            self.initialized = True

        h.fadvance()


    ###############################################################################
    # Hash function to use in generation of random value
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _id32 (self,obj): 
        return int(hashlib.md5(obj).hexdigest()[0:8],16)  # convert 8 first chars of md5 hash in base 16 to int


    def save_results(self):

        print("Saving results at t=%s..."%h.t)

        if self.sim_end < 0: self.sim_end = time.time()


        # ######################   File to save: time.dat (time)
        py_v_time = [ t/1000 for t in h.v_time.to_python() ]  # Convert to Python list for speed...

        f_time_f2 = open('time.dat', 'w')
        num_points = len(py_v_time)  # Simulation may have been stopped before tstop...

        for i in range(num_points):
            f_time_f2.write('%f'% py_v_time[i])  # Save in SI units...+ '\n')
        f_time_f2.close()
        print("Saved data to: time.dat")

        save_end = time.time()
        save_time = save_end - self.sim_end
        print("Finished saving results in %f seconds"%(save_time))

        print("Done")

        quit()


if __name__ == '__main__':

    ns = NeuronSimulation(tstop=80, dt=0.01, seed=123456789)

    ns.run()

